### ISSUE TITLE
react-native-navigation version

### ISSUE THREAD

**Issue by odub** [adamski/ReactDrum#4]
In `package.json`:
```
"react-native-navigation": "next"
```

Could you let me know what version of react-native-navigation you used when this code was last run? Setting this to `next` now means that the dependency expects a later version of react-native than 0.31.0 so the build fails.

**Comment by adamski** [comment]
It was `2.0.0-experimental.137`. It would also be worth updating to a later React Native version e.g. 0.38 or 0.40 and using the later version. I'm currently using `2.0.0-experimental.199` with RN 0.38 in the main RN + JUCE app I'm developing.
