### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by CodeJd** [adamski/ReactDrum#6]
Hi Adam,

"This project is quite out of date, based on now old versions of React Native and React Native Navigation, and also a fork of JUCE 4.3 (current version as of writing is 5.02). To be updated soon.."

thanks for the code (and all the tutorials: articles and videos), please could you tell me (more precisely) when you expect to update the project, because i would like to experiment with React + Juce for a mobile application, and this would be great.

Thanks
José

**Comment by adamski** [comment]
Hi Jose, I'm not sure, but I'll keep it mind. I'll update this thread when I get round to it. Its much more likely I'll update the iOS side, as its the Android version which requires a fork of JUCE.

**Comment by CodeJd** [comment]
Thanks for the update
